"""Report generator for weekly investment reports."""

from __future__ import annotations

from datetime import UTC, datetime
import os

from src.agent.utils.logger import get_logger
from src.config import settings

logger = get_logger(__name__)


async def generate_report(
    period_start: str,
    period_end: str | None = None,
) -> dict:
    """Generate a comprehensive investment report using the configured LLM."""
    from src.agent.clients import create_llm_client
    from src.agent.prompts import WEEKLY_REPORT_PROMPT

    end = period_end or datetime.now(UTC).strftime("%Y-%m-%d")

    prompt = WEEKLY_REPORT_PROMPT.format(period_start=period_start, period_end=end)
    system = (
        "You are an expert investment analyst. Generate a comprehensive report "
        "using the available tools to fetch all required data. Be thorough and data-driven."
    )

    client = create_llm_client()
    full_text = ""
    async for event in client.stream_response(
        messages=[{"role": "user", "content": prompt}],
        system=system,
    ):
        if event["type"] == "text_delta":
            full_text += event["text"]

    # Wrap in HTML
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Investment Report {period_start} to {end}</title>
<style>
  body {{ font-family: Georgia, serif; max-width: 900px; margin: 40px auto; padding: 0 20px;
         color: #1a1a2e; line-height: 1.7; }}
  h1 {{ color: #0f3460; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
  h2 {{ color: #16213e; margin-top: 40px; }}
  h3 {{ color: #0f3460; }}
  table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
  th {{ background: #0f3460; color: white; }}
  tr:nth-child(even) {{ background: #f8f9fa; }}
  .positive {{ color: #28a745; font-weight: bold; }}
  .negative {{ color: #dc3545; font-weight: bold; }}
  .disclaimer {{ font-size: 0.85em; color: #666; border-top: 1px solid #ddd;
                 margin-top: 40px; padding-top: 20px; }}
</style>
</head>
<body>
{_markdown_to_html(full_text)}
<div class="disclaimer">
  <strong>Disclaimer:</strong> This report is generated by an AI assistant for informational
  purposes only. It does not constitute financial advice. Always consult a qualified financial
  advisor before making investment decisions. Past performance does not guarantee future results.
</div>
</body>
</html>"""

    # Save PDF
    pdf_path = None
    try:
        import weasyprint

        os.makedirs(settings.reports_dir, exist_ok=True)
        pdf_filename = f"report_{period_start}_{end}.pdf"
        pdf_path = os.path.join(settings.reports_dir, pdf_filename)
        weasyprint.HTML(string=html_content).write_pdf(pdf_path)
        logger.info("Report PDF saved: %s", pdf_path)
    except Exception as exc:
        logger.warning("PDF generation failed (weasyprint): %s", exc)

    # Persist to DB
    try:
        from src.db.database import async_session
        from src.db.models import Report

        async with async_session() as session:
            report = Report(
                title=f"Weekly Investment Report {period_start} – {end}",
                period_start=datetime.fromisoformat(period_start).replace(tzinfo=UTC),
                period_end=datetime.fromisoformat(end).replace(tzinfo=UTC),
                html_content=html_content,
                pdf_path=pdf_path,
            )
            session.add(report)
            await session.commit()
            report_id = report.id
    except Exception as exc:
        logger.warning("Failed to persist report: %s", exc)
        report_id = None

    return {
        "success": True,
        "report_id": report_id,
        "period_start": period_start,
        "period_end": end,
        "pdf_path": pdf_path,
        "preview": full_text[:500] + "..." if len(full_text) > 500 else full_text,
    }


_HEADING_PREFIXES = (("### ", 3), ("## ", 2), ("# ", 1))


def _match_heading(line: str) -> str | None:
    for prefix, level in _HEADING_PREFIXES:
        if line.startswith(prefix):
            return f"<h{level}>{line[len(prefix) :]}</h{level}>"
    return None


def _process_text_line(line: str, in_ul: bool, html_lines: list[str], re_module) -> bool:
    """Handle a non-heading, non-list line. Returns the new in_ul state."""
    if in_ul:
        html_lines.append("</ul>")
        in_ul = False
    if line.strip():
        line = re_module.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
        html_lines.append(f"<p>{line}</p>")
    else:
        html_lines.append("")
    return in_ul


def _markdown_to_html(text: str) -> str:
    """Very basic markdown → HTML conversion."""
    import re

    lines = text.split("\n")
    html_lines: list[str] = []
    in_ul = False
    for line in lines:
        heading = _match_heading(line)
        if heading is not None:
            html_lines.append(heading)
        elif line.startswith("- ") or line.startswith("* "):
            if not in_ul:
                html_lines.append("<ul>")
                in_ul = True
            html_lines.append(f"<li>{line[2:]}</li>")
        else:
            in_ul = _process_text_line(line, in_ul, html_lines, re)
    if in_ul:
        html_lines.append("</ul>")
    return "\n".join(html_lines)
